name: TRY

on:
  pull_request:
  push:
  #schedule:
  #  - cron: "0 18 * * *" # TimeZone: UTC 0

concurrency:
  group: rocketmq-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  deploy:
    if: always()
    name: Deploy RocketMQ
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: deepsola/onetest-action@v0.2.6
        name: Deploy rocketmq
        with:
          action: "try"





  
