name: Upload-CI-TEST

on:
  push:
  #schedule:
  #  - cron: "0 18 * * *" # TimeZone: UTC 0
concurrency:
  group: rocketmq-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
jobs:
  dist-tar:
    if: always()
    name: Build dist tar
   # needs: [unit-test]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "8"
          cache: "maven"
      - name: Build distribution tar
        run: |
          mvn -Prelease-all -DskipTests clean install -U
          ls
          pwd
      - name: Tar files
        run: |
          tar -zcvf sourceCode.tar.gz *
      - uses: actions/upload-artifact@v3
        name: Upload distribution tar
        with:
          name: sourceCode
          path: sourceCode.tar.gz

  e2e-test:
    if: always()
    name: E2E Test
    needs: [dist-tar]
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/download-artifact@v3
        name: Download distribution tar
        with:
          name: sourceCode
          path: sourceCode
      - name: show information
        run: |
          ls
          cd sourceCode
          ls
          pwd
          tar -xzvf sourceCode.tar.gz
          ls
